### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by domoritz** [vega/polestar#306]
Loading the app with latest vl breaks.

**Comment by domoritz** [comment]
`'undefined' is not a function (evaluating 'element.draggable({disabled: true})')`

**Comment by kanitw** [comment]
Actually, I think there is something wrong with the test tool versions.
I remove the `node_modules` folder and run `npm install` then run `gulp test` but got the following error.


```
Error: The api interface has changed. Please use
  server = new Server(config, [done])
  server.start()
instead.
    at Object.oldServer.start (/Users/kanitw/Documents/_code/_idl/_visrec/polestar/node_modules/karma/lib/index.js:11:11)
    at runTests (/Users/kanitw/Documents/_code/_idl/_visrec/polestar/gulp/unit-tests.js:7:9)
    at Gulp.<anonymous> (/Users/kanitw/Documents/_code/_idl/_visrec/polestar/gulp/unit-tests.js:14:3)
    at module.exports (/Users/kanitw/Documents/_code/_idl/_visrec/polestar/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/kanitw/Documents/_code/_idl/_visrec/polestar/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/kanitw/Documents/_code/_idl/_visrec/polestar/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/kanitw/Documents/_code/_idl/_visrec/polestar/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/Users/kanitw/Documents/_code/_idl/_visrec/polestar/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/kanitw/Documents/_code/_idl/_visrec/polestar/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/kanitw/Documents/_code/_idl/_visrec/polestar/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/kanitw/Documents/_code/_idl/_visrec/polestar/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
    at DestroyableTransform.emit (events.js:117:20)
    at /Users/kanitw/Documents/_code/_idl/_visrec/polestar/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:419:13)
```
