### ISSUE TITLE
Cannot sandbox

### ISSUE THREAD

**Issue by domoritz** [vega/polestar#323]
If you load polestar into a sandbox, it does not initialize properly.

Create a html file like this to test it (assuming that polestar is running on port 3000. 

```html
<!DOCTYPE html>
<html>
<head>
  <title>Sandbox test</title>
  <style type="text/css">
    iframe {
      width: 100%;
      height: 500px;
    }
  </style>
</head>
<body>
<iframe src="http://localhost:3000/" sandbox="allow-scripts">
</iframe>
</body>
</html>
```

The error:
```
Error: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at Error (native)
    at http://localhost:3000/bower_components/angular/angular.js:17953:42
    at sendReq (http://localhost:3000/bower_components/angular/angular.js:10474:15)
    at serverRequest (http://localhost:3000/bower_components/angular/angular.js:10187:16)
    at processQueue (http://localhost:3000/bower_components/angular/angular.js:14634:28)
    at http://localhost:3000/bower_components/angular/angular.js:14650:27
    at Scope.$eval (http://localhost:3000/bower_components/angular/angular.js:15878:28)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:15689:31)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:15986:24)
    at bootstrapApply (http://localhost:3000/bower_components/angular/angular.js:1658:15)
```

**Comment by kanitw** [comment]
When I see this, my first question is --- why do you have to serve from gulp?  

However, I try building it and start a python SimpleHTTPServer in build folder and create a sandbox.html pointing to index.html and I run into this problem instead

```
DOMException: Failed to execute 'openDatabase' on 'Window': Access to the WebDatabase API is denied in this context.(…)openDatabase @ vendor-808c55ab5e.js:263
vendor-808c55ab5e.js:33 TypeError: Cannot read property 'createTable' of undefined
    at Object.s.createTableIfNotExists (vendor-808c55ab5e.js:325)
    at new <anonymous> (vendor-808c55ab5e.js:325)
    at r (vendor-808c55ab5e.js:32)
    at Object.o [as instantiate] (vendor-808c55ab5e.js:32)
    at Object.<anonymous> (vendor-808c55ab5e.js:32)
    at Object.r [as invoke] (vendor-808c55ab5e.js:32)
    at Object.$get (vendor-808c55ab5e.js:32)
    at Object.r [as invoke] (vendor-808c55ab5e.js:32)
    at vendor-808c55ab5e.js:32
    at i (vendor-808c55ab5e.js:32)(anonymous function) @ vendor-808c55ab5e.js:33
vendor-808c55ab5e.js:263 DOMException: Failed to execute 'openDatabase' on 'Window': Access to the WebDatabase API is denied in this context.(…)openDatabase @ vendor-808c55ab5e.js:263
vendor-808c55ab5e.js:33 TypeError: Cannot read property 'createTable' of undefined
    at Object.s.createTableIfNotExists (vendor-808c55ab5e.js:325)
    at new <anonymous> (vendor-808c55ab5e.js:325)
    at r (vendor-808c55ab5e.js:32)
    at Object.o [as instantiate] (vendor-808c55ab5e.js:32)
    at Object.<anonymous> (vendor-808c55ab5e.js:32)
    at Object.r [as invoke] (vendor-808c55ab5e.js:32)
    at Object.$get (vendor-808c55ab5e.js:32)
    at Object.r [as invoke] (vendor-808c55ab5e.js:32)
    at vendor-808c55ab5e.js:32
    at i (vendor-808c55ab5e.js:32)(anonymous function) @ vendor-808c55ab5e.js:33
vendor-808c55ab5e.js:263 DOMException: Failed to execute 'openDatabase' on 'Window': Access to the WebDatabase API is denied in this context.(…)openDatabase @ vendor-808c55ab5e.js:263
vendor-808c55ab5e.js:33 TypeError: Cannot read property 'createTable' of undefined
    at Object.s.createTableIfNotExists (vendor-808c55ab5e.js:325)
    at new <anonymous> (vendor-808c55ab5e.js:325)
    at r (vendor-808c55ab5e.js:32)
    at Object.o [as instantiate] (vendor-808c55ab5e.js:32)
    at Object.<anonymous> (vendor-808c55ab5e.js:32)
    at Object.r [as invoke] (vendor-808c55ab5e.js:32)
    at Object.$get (vendor-808c55ab5e.js:32)
    at Object.r [as invoke] (vendor-808c55ab5e.js:32)
    at vendor-808c55ab5e.js:32
    at i (vendor-808c55ab5e.js:32)(anonymous function) @ vendor-808c55ab5e.js:33
vendor-808c55ab5e.js:263 DOMException: Failed to execute 'openDatabase' on 'Window': Access to the WebDatabase API is denied in this context.(…)openDatabase @ vendor-808c55ab5e.js:263
vendor-808c55ab5e.js:33 TypeError: Cannot read property 'createTable' of undefined
    at Object.s.createTableIfNotExists (http://localhost:8000/scripts/vendor-808c55ab5e.js:325:26763)
    at new <anonymous> (http://localhost:8000/scripts/vendor-808c55ab5e.js:325:27670)
    at r (http://localhost:8000/scripts/vendor-808c55ab5e.js:32:19279)
    at Object.o [as instantiate] (http://localhost:8000/scripts/vendor-808c55ab5e.js:32:19371)
    at Object.<anonymous> (http://localhost:8000/scripts/vendor-808c55ab5e.js:32:17946)
    at Object.r [as invoke] (http://localhost:8000/scripts/vendor-808c55ab5e.js:32:19279)
    at Object.$get (http://localhost:8000/scripts/vendor-808c55ab5e.js:32:17716)
    at Object.r [as invoke] (http://localhost:8000/scripts/vendor-808c55ab5e.js:32:19279)
    at http://localhost:8000/scripts/vendor-808c55ab5e.js:32:19856
    at i (http://localhost:8000/scripts/vendor-808c55ab5e.js:32:18909) <ng-include src="'app/main/main.html'" class="ng-scope">(anonymous function) @ vendor-808c55ab5e.js:33
vendor-808c55ab5e.js:263 DOMException: Failed to execute 'openDatabase' on 'Window': Access to the WebDatabase API is denied in this context.(…)openDatabase @ vendor-808c55ab5e.js:263
vendor-808c55ab5e.js:33 TypeError: Cannot read property 'createTable' of undefined
    at Object.s.createTableIfNotExists (vendor-808c55ab5e.js:325)
    at new <anonymous> (vendor-808c55ab5e.js:325)
    at r (vendor-808c55ab5e.js:32)
    at Object.o [as instantiate] (vendor-808c55ab5e.js:32)
    at Object.<anonymous> (vendor-808c55ab5e.js:32)
    at Object.r [as invoke] (vendor-808c55ab5e.js:32)
    at Object.$get (vendor-808c55ab5e.js:32)
    at Object.r [as invoke] (vendor-808c55ab5e.js:32)
    at vendor-808c55ab5e.js:32
    at i (vendor-808c55ab5e.js:32)(anonymous function) @ vendor-808c55ab5e.js:33
chrome-extension://iebpjdmgckacbodjpijphcplhebcmeop/js/content.scripts.c.js:11 TableManager::findTables()
```

**Comment by kanitw** [comment]
Its's very wierd .. even if I put return; in front of the methods in logger.js it still throw this error. 

There must be something wrong with the gulp that makes it outdated.  

I gotta go for now though

**Comment by domoritz** [comment]
Gulp doesn't seem to be the issue. I already removed all webdb stuff (you need to clear your bower directories!). Even with a production build, I get this error

```
Error: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at Error (native)
    at E (http://localhost:9000/scripts/vendor-19176a3487.js:235:4076)
    at Object.x [as get] (http://localhost:9000/scripts/vendor-19176a3487.js:235:1798)
    at o.load (http://localhost:9000/scripts/vendor-19176a3487.js:308:18233)
    at new <anonymous> (http://localhost:9000/scripts/app-fe975ed36f.js:32:10264)
    at Object.r [as invoke] (http://localhost:9000/scripts/vendor-19176a3487.js:32:19340)
    at f.instance (http://localhost:9000/scripts/vendor-19176a3487.js:33:9432)
    at m (http://localhost:9000/scripts/vendor-19176a3487.js:32:31017)
    at s (http://localhost:9000/scripts/vendor-19176a3487.js:32:27476)
    at http://localhost:9000/scripts/vendor-19176a3487.js:32:26917 <ng-include src="'app/main/main.html'" class="ng-scope">(anonymous function) @ vendor-19176a3487.js:33(anonymous function) @ vendor-19176a3487.js:33rt @ vendor-19176a3487.js:33m @ vendor-19176a3487.js:32s @ vendor-19176a3487.js:32(anonymous function) @ vendor-19176a3487.js:32P.i @ vendor-19176a3487.js:32l @ vendor-19176a3487.js:32(anonymous function) @ vendor-19176a3487.js:37u @ vendor-19176a3487.js:33(anonymous function) @ vendor-19176a3487.js:33d.$eval @ vendor-19176a3487.js:34d.$digest @ vendor-19176a3487.js:34d.$apply @ vendor-19176a3487.js:34(anonymous function) @ vendor-19176a3487.js:32r @ vendor-19176a3487.js:32s @ vendor-19176a3487.js:32at @ vendor-19176a3487.js:32ot @ vendor-19176a3487.js:32(anonymous function) @ vendor-19176a3487.js:37c @ vendor-19176a3487.js:24f.fireWith @ vendor-19176a3487.js:24Q.extend.ready @ vendor-19176a3487.js:24a @ vendor-19176a3487.js:14
(index):4 GET http://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT(anonymous function) @ (index):4(anonymous function) @ (index):5
```

**Comment by kanitw** [comment]
I see -- looking at our bower dependency list -- looks like chronicle is the most suspicious for using cookie.

**Comment by domoritz** [comment]
I doubt it https://github.com/Blitzen/Angular-Chronicle/search?utf8=%E2%9C%93&q=cookie

**Comment by kanitw** [comment]
The culprit is  https://github.com/grevory/angular-local-storage  I believe.  
Since it has cookie fallback.  

Removing/replacing it for now could be a patch -- as we only depend on it for bookmark.

**Comment by domoritz** [comment]
Fixed.
